function plot2ddb(net,X,z,res,thresh)
% plot2ddb(net,X,z,res,thresh)
% Plots a decision boundary in 2-D generated by an matlab MLP object.
%
% net    - a trained mlp object with 2 inputs and one output
% X      - 2-D input data
% z      - corresponding target data
% res    - a switch 'h' or 'l' for a high or low resolution graph
% thresh - the threshold value (posterior probability value at which decision is made)
%
% (c) 2001 The University of Sheffield

switch lower(res)
case {'h','hi','high'}
    npts=500;
case {'l','lo','low'}
    npts=20;
end
minmax=[min([X])' max([X])'];
[X1,X2]=meshgrid(linspace(minmax(1,1),minmax(1,2),npts),linspace(minmax(2,1),minmax(2,2),npts));
x=[X1(:) X2(:)];
% y=sim(net,x'); if using NNT
if net.type=='mlp'
    y=mlpfwd(net,x);
elseif net.type=='glm'
    y=glmfwd(net,x);
elseif net.type=='rbf'
    y=rbffwd(net,x);
elseif net.type=='klr'
    y=klrfwd(net,x);
end
Y=reshape(y',npts,npts);
contour(X1,X2,Y,[thresh thresh],'r');
hold on
plot(X(find(z==1),1),X(find(z==1),2),'+',X(find(z==0),1),X(find(z==0),2),'o');%axis([minmax(1,1) minmax(1,2) minmax(2,1) minmax(2,2)]);
hold off
